### ISSUE TITLE
README.md misspellings

### ISSUE THREAD

**Issue by andrasfuchs** [STSSoft/DatabaseBenchmark#2]
There are a few misspellings in the readme.md:

"most powerfull open source" ->  "most powerful open source"
"is a very powerfull stress test tool" -> "is a very powerful stress test tool"

"Graphic Vsualization" looks like it is misspelled in both the README.md and on the website (http://stssoft.com/products/database-benchmark/). Is it on purpose?

**Comment by ChrisDimitrov** [comment]
Thank you for the corrections.
