### ISSUE TITLE
Feature Request: Add siaqodb database

### ISSUE THREAD

**Issue by andrasfuchs** [STSSoft/DatabaseBenchmark#5]
Siaqodb is a NoSQL embedded object & document database engine that can be used to make apps for .NET, WindowsStore, WindowsPhone, Mono, MonoMac, Xamarin.iOS, Xamarin.Android and Unity3D.

Please add support for it. The nuget package is available here:
https://www.nuget.org/packages/Siaqodb/

**Comment by ChrisDimitrov** [comment]
We had some issues with the **siaqodb** development team. They were not very pleased with their database being present in Database Benchmark, so we had to remove it.
